# Mandatory settings

blog_theme: light # Dark or light
name: Preston Carpenter's Blog
paginate: 25
url: https://timidger.github.io # add your site url (format: https://example.com)


# Optional settings

about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
baseurl: # Set if blog doesn't sit at the root of the domain (format: /blog)
ga_analytics: UA-113741520-1
local_fonts: true
rss_enabled: false
scrollappear_enabled: true # Change to false to disable
social:
  github: timidger
  linkedin: timidger
  twitter: timidger
  email: APragmaticPlace@gmail.com
  stackoverflow: 1772476/timidger

# Important settings (change at own risk)

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: posts/:slug
